apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: remove
      image: bitnami/kubectl
      script: |
        #!/usr/bin/env bash
        rm -rf /workspace/output/*
        rm -rf /workspace/output/.[!.]*
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source
  steps:
    - name: nose-test
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        pip install -r requirements.txt
        pip install nose
        nosetests -v
